services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pokemon.csv:/etc/pokemon.csv
